stages:
  - build
  - test
  - release

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - frontend/node_modules/

build-backend:
  stage: build
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/sausage-store-*.jar
    expire_in: 1 week
  tags:
    - shell

build-frontend:
  stage: build
  only:
    changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 week
  tags:
    - shell

test-backend:
  stage: test
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - mvn test
  dependencies:
    - build-backend
  tags:
    - shell

create-release-artifact:
  stage: release
  only:
    - release-0.0.1
  script:
    - mkdir -p sausage-store-0.0.1
    - cp backend/target/sausage-store-*.jar sausage-store-0.0.1/sausage-store-0.0.1.jar
    - cp -r frontend/dist sausage-store-0.0.1/public_html
    - tar -czf sausage-store-0.0.1.tar.gz sausage-store-0.0.1/
  artifacts:
    paths:
      - sausage-store-0.0.1.tar.gz
    expire_in: 1 month
  dependencies:
    - build-backend
    - build-frontend
  tags:
    - shell
